export const dummyResponse = {
    data: [
        {
            id: 1,
            name: 'Alvin Satterfield',
            email: 'cornellbartell@connellyleannon.biz',
            birth_date: '1997-09-07',
            year_of_experience: 5,
            position_applied: 'Technician',
            application_date: '2018-07-02',
            status: 'rejected',
        },
        {
            id: 2,
            name: 'Colette Morar',
            email: 'corinnestark@pacocha.co',
            birth_date: '1998-08-03',
            year_of_experience: 3,
            position_applied: 'Designer',
            application_date: '2017-11-18',
            status: 'waiting',
        },
        {
            id: 3,
            name: 'Rosalind Rath DDS',
            email: 'sandyankunding@marks.io',
            birth_date: '1980-03-28',
            year_of_experience: 15,
            position_applied: 'Orchestrator',
            application_date: '2018-01-31',
            status: 'approved',
        },
        {
            id: 4,
            name: 'Cyrstal Kunze',
            email: 'lavernokon@stroman.name',
            birth_date: '1997-10-30',
            year_of_experience: 8,
            position_applied: 'Analyst',
            application_date: '2018-09-12',
            status: 'rejected',
        },
        {
            id: 5,
            name: 'Henrietta Fisher V',
            email: 'lewis@sipes.biz',
            birth_date: '1974-09-14',
            year_of_experience: 14,
            position_applied: 'Producer',
            application_date: '2018-04-25',
            status: 'waiting',
        },
        {
            id: 6,
            name: 'Michal Kiehn Sr.',
            email: 'ruelmarks@prohaska.co',
            birth_date: '1976-08-04',
            year_of_experience: 1,
            position_applied: 'Planner',
            application_date: '2018-04-05',
            status: 'rejected',
        },
        {
            id: 7,
            name: 'Lavonda Murazik',
            email: 'mayesimonis@white.name',
            birth_date: '1984-04-25',
            year_of_experience: 6,
            position_applied: 'Administrator',
            application_date: '2018-10-06',
            status: 'waiting',
        },
        {
            id: 8,
            name: 'Herman Altenwerth',
            email: 'wavavonrueden@brekkecasper.org',
            birth_date: '1996-08-08',
            year_of_experience: 2,
            position_applied: 'Liaison',
            application_date: '2018-09-14',
            status: 'waiting',
        },
        {
            id: 9,
            name: 'Ernestina Dicki',
            email: 'lawrencekunze@pouros.io',
            birth_date: '1971-09-01',
            year_of_experience: 14,
            position_applied: 'Associate',
            application_date: '2018-07-13',
            status: 'approved',
        },
        {
            id: 10,
            name: 'Deedee Kuhic',
            email: 'karisa@mertz.co',
            birth_date: '1973-08-30',
            year_of_experience: 2,
            position_applied: 'Strategist',
            application_date: '2018-10-08',
            status: 'waiting',
        },
        {
            id: 11,
            name: 'Carmela Hilll Sr.',
            email: 'hermelindalang@barrows.org',
            birth_date: '1984-10-04',
            year_of_experience: 11,
            position_applied: 'Assistant',
            application_date: '2018-10-10',
            status: 'waiting',
        },
        {
            id: 12,
            name: 'Brandon Hilll',
            email: 'vondalangosh@bosco.org',
            birth_date: '1986-02-03',
            year_of_experience: 5,
            position_applied: 'Representative',
            application_date: '2018-04-11',
            status: 'rejected',
        },
    ],
};
